name: nf-core version comment
# This workflow is triggered on PRs to check if the pipeline template version if the latest.
on:
  pull_request_target:

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Read template version from .nf-core.yml
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_yml
        with:
          config: ${{ github.workspace }}/.nf-core.yml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nf-core==${{ steps.read_yml.outputs['nf_core_version'] }}

      - name: Check nf-core outdated
        id: nf_core_outdated
        run: pip list --outdated | grep nf-core

      - name: Post nf-core last version comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        if: |
          ${{ steps.nf_core_outdated.outputs.stdout }} =~ 'nf-core'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false
          message: |
            ## :warning: New nf-core template version available

            Your pipeline is using an old version of the nf-core template: ${{ steps.read_yml.outputs['nf_core_version'] }}.
            Please update your pipeline to the latest version.
